Added mailboxes feature to specify folders to retrieve mail from
NethServer/nethserver-getmail pull request #4
Opened 2017-03-29 07:20 UTC by Bartonline

See [http://community.nethserver.org/t/ability-to-select-mailbox-with-pop3-connector/6370](url)

2017-03-29 08:59 UTC, DavidePrincipi requested changes

2017-03-29 08:59 UTC, DavidePrincipi commented on root/etc/e-smith/templates/getmailrc/10retriever
> +    if ((uc $mailbox) eq 'ALL' ) {
We must disable the "Mailbox" prop effects if "Retriever" is not IMAP (POP3 does not support server-side folders)

2017-03-31 06:37 UTC, DavidePrincipi approved these changes

2017-03-31 07:03 UTC, DavidePrincipi requested changes
Please, trim any possible white space around the mailbox elements

2017-03-31 07:03 UTC, DavidePrincipi commented on root/etc/e-smith/templates/getmailrc/10retriever
> +        $mailbox =~ s/,/\",\"/g;
As the UI allows "ANYTHING" here we should (at least) trim spaces. i.e. ``Folder1, Folder2,   Folder3`` produces ``("Folder1","Folder2","Folder3")``.

2017-03-31 07:03 UTC, DavidePrincipi commented on root/usr/share/nethesis/NethServer/Module/Getmail/Modify.php
> +            array('Mailbox', Validate::ANYTHING, \Nethgui\Controller\Table\Modify::FIELD),
I'd prefer a stronger validation. A similar issue has been addressed here

https://github.com/NethServer/nethserver-mail-common/blob/master/root/usr/share/nethesis/NethServer/Module/Mail/SmtpAccess.php#L37-L56

The ``readAccessBypassList()`` and ``writeAccessBypassList()`` are invoked by the framework when the DB prop is read/written respectively.

The element split procedure also trims surrounding whitespaces.

2017-03-31 07:03 UTC, DavidePrincipi commented on root/usr/share/nethesis/NethServer/Template/Getmail/Modify.php
> +    ->insert($view->textInput('Mailbox'))
If more than one element is allowed, we could use a ``textArea()``, as previous code example does.

2017-03-31 11:40 UTC, Bartonline commented on root/etc/e-smith/templates/getmailrc/10retriever
> +        $mailbox =~ s/,/\",\"/g;
Hi Davide, thank you for your feedback. I'll look into it, might take me some time to figure out nethserver works internaly. Please be patient ;-)

2017-03-31 11:41 UTC, Bartonline commented on root/usr/share/nethesis/NethServer/Module/Getmail/Modify.php
> +            array('Mailbox', Validate::ANYTHING, \Nethgui\Controller\Table\Modify::FIELD),
Ok, I will look into it.

2017-03-31 11:42 UTC, Bartonline commented on root/usr/share/nethesis/NethServer/Template/Getmail/Modify.php
> +    ->insert($view->textInput('Mailbox'))
I'll have a look at textArea().

2017-04-18 14:33 UTC, gsanchietti commented
I would like to have this PR merged.

@Bartonline did you have time to fix requested changes?
Otherwise @DavidePrincipi could eventually push the needed fixed to the PR.

2017-04-18 17:34 UTC, Bartonline commented
Hi @gsanchietti ,

I did use textArea(), which was easy, but have not yet commited the changes. Unfortunately, I stumbled upon another problem. Somehow it seems as if the mailboxes-parameter does not work at all!?! I've been trying to pinpoint the problem, but have not found it yet. If I enter a folder-name (anything besides 'ALL'), getmail will do nothing, meaning I don't see a line like `2017-04-10 20:40:01 Initializing SimpleIMAPSSLRetriever:myname@imap.xs4all.nl:993:` in the getmail logging.

2017-06-20 06:55 UTC, gsanchietti commented
Hi @Bartonline,
did you find a solution?

2017-06-26 08:36 UTC, gsanchietti commented
Closing for now, reopen if you find a working implementation ;)

2017-06-26 08:36 UTC, closed without merging